pipeline{
    agent any
   
}
    stages{
        stage('Install'){
            agent { docker { image 'node:20-alpine' } }
            steps{
                dir('projet-02-node-test'){
                    sh 'npm ci'
                }
            }
        }
        stage('Test'){
            agent { docker { image 'node:20-alpine' } }
            steps{
                dir('projet-02-node-test'){
                    echo 'Executions des testes...'
                    sh 'npm test'
                }
            }
        }
        stage('Build'){
            steps{
                echo '===== Build de l\\image docker ====='
                dir('projet-02-node-test'){
                     sh 'docker build -t project02:${BUILD_NUMBER} .'
                }  
            }
        }
        stage('verify container'){
            steps{
                sh '''
                docker run -d --name test-project02 -p 4002:3000 project02:${BUILD_NUMBER}
                sleep 5
                curl -f http://localhost:4002/health || exit 1
                docker stop test-project02
                docker rm test-project02
                '''
            }
        }
    }
    post {
        failure {
            echo 'Pipeline ECHOUE - vérifier les logs'
        }
        always {
           sh 'docker rm -f test-project02 || true'
        }
    }
}