version: '3.8'

services:
  app:
    image: ${IMAGE_NAME}:${TAG}
    ports:
     - "80:3000"
    environment:
     - NODE_ENV=production
    restart: always
    deploy:
     resources:
       limits:
         memory: 256M
         cpus: '0.5'
