pipeline{
    agent any
    tool {
        nodejs 'node20'
    }
    triggers{
        gitlab(
            triggerOnPush:true
        )
    }
    environment{
        IMAGE_NAME ='registry:5000/project03'
    }
    stages{
        stage('Build'){
            steps{
                sh 'docker build -t ${IMAGE_NAME}:{BUILD_NUMBER} .'
                sh 'docker tag ${IMAGE_NAME}:{BUILD_NUMBER} ${IMAGE_NAME}:latest'
            }
        }
        stage('test'){
            steps{
                sh '''
                docker run -d --name test-project03 --network devops-exercices_default ${IMAGE_NAME}:{BUILD_NUMBER}
                sleep 5
                curl -f http://test-project03:3000/health || exit 1
                docker stop test-project03 && docker rm test-project03
                '''
            }
        }
        stage('push to registry'){
           steps{
             sh '''
            docker push ${IMAGE_NAME}:${BUILD_NUMBER}
            docker push ${IMAGE_NAME}:latest
            '''
           }
        }
        post{
            always{
                sh 'docker rm -f test-projet03'
            }
            failure{
                echo 'pipeline Failed'
            }
            success{
                echo 'pipeline succes'
            }
        }

    }
}