version: '3.8'

services:
  gateway:
    build: ./api-gateway
    ports:
    - "8080:8080"
    depends-on:
    - user-service
    - product-service

  user-service:
    build: ./user-service
    ports:
    - "3000"

  product-service:
    build: ./product-service
    ports:
    - "3000"