pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('projet-01-html-basic') {
                    sh 'docker build -t project01:${BUILD_NUMBER} .'
                }
            }
        }
        stage('Test') {
            steps {
                sh '''
                    docker run -d --name project01 -p 9001:80 project01:${BUILD_NUMBER}
                    sleep 2
                    curl -f http://localhost:9001 || exit 1
                    docker stop project01 && docker rm project01
                '''
            }
        }
    }

    post {
        always {
            sh 'docker rm -f project01 || true'
        }
    }
}
