name: PROJET 03 - push to dockerhub

on: 
  push: 
    paths: 
      - 'projet-03-push-dockerhub'
      - '.github/workflows/projet03.yml'
  workflow_dispatch: 

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{secrets.DOCKERHUB_USERNAME}}/projet03
    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        working-directory: projet-03-push-dockerhub
        run: docker  build -t $IMAGE_NAME:${{github.sha}} .

      - name: Test container
        working-directory: projet-03-push-dockerhub
        run: |
          docker run -d --name test-pp03 -p 4003:3000 $IMAGE_NAME:${{github.sha}}
          sleep 2
          curl http://localhost:4003/health || exit 1
          docker rm -f test-p03

      - name: Login in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push to dockerhub
        working-directory: projet-03-push-dockerhub
        run: |
          docker tag $IMAGE_NAME:${{github.sha}} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{github.sha}}
          docker push $IMAGE_NAME:latest 
